// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page1_start

#ifndef _PAGE1_START_UI_H
#define _PAGE1_START_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_page1_Screen_Start
void ui_page1_Screen_Start_screen_init(void);
extern lv_obj_t * ui_page1_Screen_Start;
extern lv_obj_t * ui_page1_Bar_loading;
extern lv_obj_t * ui_page1_Label_loading_text;
extern lv_obj_t * ui_page1_Image_png;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_xiyi_png);    // assets/images/xiyi.png

// FONTS
LV_FONT_DECLARE(ui_font_Font20px);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
