// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page1_start

#include "ui.h"

void ui_page1_Screen_Start_screen_init(void)
{
    ui_page1_Screen_Start = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_page1_Screen_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page1_Bar_loading = lv_bar_create(ui_page1_Screen_Start);
    lv_bar_set_value(ui_page1_Bar_loading, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_page1_Bar_loading, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_page1_Bar_loading, 550);
    lv_obj_set_height(ui_page1_Bar_loading, 20);
    lv_obj_set_x(ui_page1_Bar_loading, 15);
    lv_obj_set_y(ui_page1_Bar_loading, 70);
    lv_obj_set_align(ui_page1_Bar_loading, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_page1_Bar_loading, lv_color_hex(0xD6D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page1_Bar_loading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page1_Label_loading_text = lv_label_create(ui_page1_Screen_Start);
    lv_obj_set_width(ui_page1_Label_loading_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page1_Label_loading_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page1_Label_loading_text, 5);
    lv_obj_set_y(ui_page1_Label_loading_text, 105);
    lv_obj_set_align(ui_page1_Label_loading_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page1_Label_loading_text, "正在连接wifi");
    lv_obj_set_style_text_font(ui_page1_Label_loading_text, &ui_font_Font20px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page1_Image_png = lv_img_create(ui_page1_Screen_Start);
    lv_img_set_src(ui_page1_Image_png, &ui_img_images_xiyi_png);
    lv_obj_set_width(ui_page1_Image_png, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page1_Image_png, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page1_Image_png, -2);
    lv_obj_set_y(ui_page1_Image_png, -42);
    lv_obj_set_align(ui_page1_Image_png, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page1_Image_png, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page1_Image_png, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
