// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page1_start

#ifndef _PAGE1_START_UI_H
#define _PAGE1_START_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN1: ui_page1_Screen_Start 启动页面  
void ui_page1_Screen_Start_screen_init(void);
extern lv_obj_t * ui_page1_Screen_Start;
extern lv_obj_t * ui_page1_Bar_loading;
extern lv_obj_t * ui_page1_Label_loading_text;
extern lv_obj_t * ui_page1_Image_png;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_xiyi_png);    // assets/images/xiyi.png
LV_IMG_DECLARE(fengche);

// FONTS
LV_FONT_DECLARE(ui_font_Font20px);


// SCREEN2: ui_page2_screen_weather 天气页面
void ui_page2_screen_weather_screen_init(void);
extern lv_obj_t * ui_page2_screen_weather;
extern lv_obj_t * ui_page2_panel_main;
extern lv_obj_t * ui_page2_panel_main_label_date;
extern lv_obj_t * ui_page2_panel_main_label_week;
extern lv_obj_t * ui_page2_panel_main_label_lunar;
extern lv_obj_t * ui_page2_panel_main_label_time;
extern lv_obj_t * ui_page2_panel_main_label_suggest;
extern lv_obj_t * ui_page2_image_current_weather;
extern lv_obj_t * ui_page2_panel_main_label_current_temp;
extern lv_obj_t * ui_page2_panel_main_label_current_text;
extern lv_obj_t * ui_page2_panel_main_panel_temphub;
extern lv_obj_t * ui_page2_panel_main_label_inroom;
extern lv_obj_t * ui_page2_panel_main_label_inroom_temp;
extern lv_obj_t * ui_page2_panel_main_label_inroom_hub;
extern lv_obj_t * ui_page2_panel_main_image_temp;
extern lv_obj_t * ui_page2_panel_main_image_temp2;
extern lv_obj_t * ui_page2_panel_main_warn;
extern lv_obj_t * ui_page2_panel_main_label_current_temp2;
extern lv_obj_t * ui_page2_image_current_weather_day1;
extern lv_obj_t * ui_page2_image_current_weather_day2;
extern lv_obj_t * ui_page2_image_current_weather_day3;
extern lv_obj_t * ui_page2_panel_main_label_current_day1;
extern lv_obj_t * ui_page2_panel_main_label_current_day2;
extern lv_obj_t * ui_page2_panel_main_label_current_day3;
extern lv_obj_t * ui_page2_panel_main_label_current_day1_temp;
extern lv_obj_t * ui_page2_panel_main_label_current_day2_temp;
extern lv_obj_t * ui_page2_panel_main_label_current_day3_temp;
extern lv_obj_t * ui_page2_image_localtion;
extern lv_obj_t * ui_page2_label_location;
extern lv_obj_t * ui_page2_label_update;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_bizhi_png);    // assets/images/bizhi.png
LV_IMG_DECLARE(ui_img_images_m00_png);    // assets/images/m00.png
LV_IMG_DECLARE(ui_img_images_temp_png);    // assets/images/temp.png
LV_IMG_DECLARE(ui_img_images_hub_png);    // assets/images/hub.png
LV_IMG_DECLARE(ui_img_images_m01_png);    // assets/images/m01.png
LV_IMG_DECLARE(ui_img_images_m02_png);    // assets/images/m02.png
LV_IMG_DECLARE(ui_img_images_m08_png);    // assets/images/m08.png
LV_IMG_DECLARE(ui_img_images_location_png);    // assets/images/location.png
LV_IMG_DECLARE(ui_img_images_m03_png);    // assets/images/m03.png
LV_IMG_DECLARE(ui_img_images_m04_png);    // assets/images/m04.png
LV_IMG_DECLARE(ui_img_images_m05_png);    // assets/images/m05.png
LV_IMG_DECLARE(ui_img_images_m06_png);    // assets/images/m06.png
LV_IMG_DECLARE(ui_img_images_m07_png);    // assets/images/m07.png
LV_IMG_DECLARE(ui_img_images_m09_png);    // assets/images/m09.png
LV_IMG_DECLARE(ui_img_images_m10_png);    // assets/images/m10.png
LV_IMG_DECLARE(ui_img_images_m11_png);    // assets/images/m11.png
LV_IMG_DECLARE(ui_img_images_m12_png);    // assets/images/m12.png
LV_IMG_DECLARE(ui_img_images_m13_png);    // assets/images/m13.png
LV_IMG_DECLARE(ui_img_images_m14_png);    // assets/images/m14.png
LV_IMG_DECLARE(ui_img_images_m15_png);    // assets/images/m15.png
LV_IMG_DECLARE(ui_img_images_m16_png);    // assets/images/m16.png
LV_IMG_DECLARE(ui_img_images_m17_png);    // assets/images/m17.png

LV_IMG_DECLARE(yin); 
LV_IMG_DECLARE(qing); 
LV_IMG_DECLARE(duoyun); 
LV_IMG_DECLARE(xiaoyu); 
LV_IMG_DECLARE(baoyu); 
LV_IMG_DECLARE(dayu); 
LV_IMG_DECLARE(zhongyu); 
LV_IMG_DECLARE(zhenyu); 
LV_IMG_DECLARE(yu); 
LV_IMG_DECLARE(leizhenyu); 
LV_IMG_DECLARE(dabaoyu); 
LV_IMG_DECLARE(tedabaoyu); 
LV_IMG_DECLARE(dongyu); 
LV_IMG_DECLARE(baoxue); 
LV_IMG_DECLARE(daxue); 
LV_IMG_DECLARE(zhongxue); 
LV_IMG_DECLARE(xiaoxue); 
LV_IMG_DECLARE(yujiaxue); 
LV_IMG_DECLARE(xue); 
LV_IMG_DECLARE(bingbao); 
LV_IMG_DECLARE(fuchen); 
LV_IMG_DECLARE(yangsha); 
LV_IMG_DECLARE(shachenbao); 
LV_IMG_DECLARE(dawu); 
LV_IMG_DECLARE(wu); 
LV_IMG_DECLARE(mai); 


// FONTS
LV_FONT_DECLARE(ui_font_Font38px);
LV_FONT_DECLARE(ui_font_Font18px);
LV_FONT_DECLARE(ui_font_Font102px);


// SCREEN: ui_page3_screen_monitor  监控页面
void ui_page3_screen_monitor_screen_init(void);
extern lv_obj_t * ui_page3_screen_monitor;
extern lv_obj_t * ui_page3_panel_cpu;
extern lv_obj_t * ui_page3_label_cpu_text;
extern lv_obj_t * ui_page3_arc_cpu_use;
extern lv_obj_t * ui_page3_image_cpu;
extern lv_obj_t * ui_page3_label_cpu_use_;
extern lv_obj_t * ui_page3_label_cpu_use_text;
extern lv_obj_t * ui_page3_label_cpu_use_temp;
extern lv_obj_t * ui_page3_label_cpu_freq;
extern lv_obj_t * ui_page3_label_cpu_fanspeed;
extern lv_obj_t * ui_page3_panel_gpu;
extern lv_obj_t * ui_page3_label_gpu_text;
extern lv_obj_t * ui_page3_arc_gpu_use;
extern lv_obj_t * ui_page3_image_gpu;
extern lv_obj_t * ui_page3_label_gpu_use;
extern lv_obj_t * ui_page3_label_gpu_use_text;
extern lv_obj_t * ui_page3_label_gpu_use_temp;
extern lv_obj_t * ui_page3_label_gpu_freq;
extern lv_obj_t * ui_page3_label_gpu_fanspeed;
extern lv_obj_t * ui_page3_panel_mem;
extern lv_obj_t * ui_page3_label_mem_text;
extern lv_obj_t * ui_page3_arc_mem_use;
extern lv_obj_t * ui_page3_label_mem_use_text;
extern lv_obj_t * ui_page3_image_mem;
extern lv_obj_t * ui_page3_label_mem_use_;
extern lv_obj_t * ui_page3_panel_net;
extern lv_obj_t * ui_page3_image_net_upload;
extern lv_obj_t * ui_page3_image_net_download;
extern lv_obj_t * ui_page3_label_download_speed;
extern lv_obj_t * ui_page3_label_uploadspeed;
extern lv_obj_t * ui_page3_label_cpu_tdp;
extern lv_obj_t * ui_page3_label_gpu_tdp;
extern lv_obj_t * ui_page3_image_gpu2;
extern lv_obj_t * ui_page3_image_cpu2;
extern lv_obj_t * ui_page3_label_cpu_fanspeed2;
extern lv_obj_t * ui_page3_label_net_speed_text;
extern lv_obj_t * ui_page3_panel_time;
extern lv_obj_t * ui_page3_label_cpu_fanspeed3;
extern lv_obj_t * ui_page3_label_cpu_fanspeed4;
extern lv_obj_t * ui_page3_label_download_speed2;
extern lv_obj_t * ui_page3_label_gpu_use2;
extern lv_obj_t * ui_page3_panel_others;
extern lv_obj_t * ui_page3_label_net_speed_text2;
// CUSTOM VARIABLES

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_cpu_png);    // assets/images/CPU.png
LV_IMG_DECLARE(ui_img_1298787339);    // assets/images/gpu-mining.png
LV_IMG_DECLARE(ui_img_images_ram_png);    // assets/images/RAM.png
LV_IMG_DECLARE(ui_img_images_upload_png);    // assets/images/upload.png
LV_IMG_DECLARE(ui_img_images_download_png);    // assets/images/download.png

// FONTS
LV_FONT_DECLARE(ui_font_Font18mkzpx);
LV_FONT_DECLARE(ui_font_Font18px);
LV_FONT_DECLARE(ui_font_Font24px);
LV_FONT_DECLARE(ui_font_Font48px);

// SCREEN: ui_page4_screen_set_about  设置关于
void ui_page4_screen_set_about_screen_init(void);
extern lv_obj_t * ui_page4_screen_set_about;
extern lv_obj_t * ui_page4_panel_about;
extern lv_obj_t * ui_page4_label_about_version;
extern lv_obj_t * ui_page4_label_about_name;
extern lv_obj_t * ui_page4_label_about_designed_by;
extern lv_obj_t * ui_page4_panel_wifi_info;
extern lv_obj_t * ui_page4_label_wifi_info_title;
extern lv_obj_t * ui_page4_panel_wifi_connection_status;
extern lv_obj_t * ui_page4_label_wifi_connection_status;
extern lv_obj_t * ui_page4_panel_wifi_ip_address;
extern lv_obj_t * ui_page4_label_wifi_ip_address;
extern lv_obj_t * ui_page4_panel_wifi_signal_strength;
extern lv_obj_t * ui_page4_label_wifi_signal_strength;
extern lv_obj_t * ui_page4_panel_comm;
extern lv_obj_t * ui_page4_label_comm_titile;
extern lv_obj_t * ui_page4_panel_bilibili_name;
extern lv_obj_t * ui_page4_label_bilibili_name;
extern lv_obj_t * ui_page4_panel_qq_num;
extern lv_obj_t * ui_page4_label_qq_num;
extern lv_obj_t * ui_page4_panel_communication_group_;
extern lv_obj_t * ui_page4_label_communication_group_;
extern lv_obj_t * ui_page4_panel_set_mode;
extern lv_obj_t * ui_page4_label_set_mode_title;
extern lv_obj_t * ui_page4_panel_set_mode_info;
extern lv_obj_t * ui_page4_label_set_mode_info;


// SCREEN: ui_page5_screen_main
void ui_page5_screen_main_screen_init(void);
extern lv_obj_t * ui_page5_screen_main;
extern lv_obj_t * ui_page5_image_background;
extern lv_obj_t * ui_page5_label_time;
extern lv_obj_t * ui_page5_label_date;

// CUSTOM VARIABLES
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_Label2;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_bizhi_yejing1_png);    // assets/images/bizhi_yejing1.png
LV_IMG_DECLARE(ui_img_images_bizhi_yanhua1_png);    // assets/images/bizhi_yanhua1.png

// FONTS
LV_FONT_DECLARE(ui_font_Font22px);
LV_FONT_DECLARE(ui_font_Font82px);


// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
