// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page4_set&about

#ifndef _PAGE4_SET&ABOUT_UI_H
#define _PAGE4_SET&ABOUT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_page4_screen_set_about
void ui_page4_screen_set_about_screen_init(void);
extern lv_obj_t * ui_page4_screen_set_about;
extern lv_obj_t * ui_page4_panel_about;
extern lv_obj_t * ui_page4_label_about_version;
extern lv_obj_t * ui_page4_label_about_name;
extern lv_obj_t * ui_page4_label_about_designed_by;
extern lv_obj_t * ui_page4_panel_wifi_info;
extern lv_obj_t * ui_page4_label_wifi_info_title;
extern lv_obj_t * ui_page4_panel_wifi_connection_status;
extern lv_obj_t * ui_page4_label_wifi_connection_status;
extern lv_obj_t * ui_page4_panel_wifi_ip_address;
extern lv_obj_t * ui_page4_label_wifi_ip_address;
extern lv_obj_t * ui_page4_panel_wifi_signal_strength;
extern lv_obj_t * ui_page4_label_wifi_signal_strength;
extern lv_obj_t * ui_page4_panel_comm;
extern lv_obj_t * ui_page4_label_comm_titile;
extern lv_obj_t * ui_page4_panel_bilibili_name;
extern lv_obj_t * ui_page4_label_bilibili_name;
extern lv_obj_t * ui_page4_panel_qq_num;
extern lv_obj_t * ui_page4_label_qq_num;
extern lv_obj_t * ui_page4_panel_communication_group_;
extern lv_obj_t * ui_page4_label_communication_group_;
extern lv_obj_t * ui_page4_panel_set_mode;
extern lv_obj_t * ui_page4_label_set_mode_title;
extern lv_obj_t * ui_page4_panel_set_mode_info;
extern lv_obj_t * ui_page4_label_set_mode_info;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Font18px);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
