// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page1_start

#include "../include/ui_h/ui.h"
#include "../include/ui_h/ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN1: ui_page1_Screen_Start 启动页面
void ui_page1_Screen_Start_screen_init(void);
lv_obj_t * ui_page1_Screen_Start;
lv_obj_t * ui_page1_Bar_loading;
lv_obj_t * ui_page1_Label_loading_text;
lv_obj_t * ui_page1_Image_png;

// SCREEN2: ui_page2_screen_weather 天气页面
void ui_page2_screen_weather_screen_init(void);
lv_obj_t * ui_page2_screen_weather;
lv_obj_t * ui_page2_panel_main;
lv_obj_t * ui_page2_panel_main_label_date;
lv_obj_t * ui_page2_panel_main_label_week;
lv_obj_t * ui_page2_panel_main_label_lunar;
lv_obj_t * ui_page2_panel_main_label_time;
lv_obj_t * ui_page2_panel_main_label_suggest;
lv_obj_t * ui_page2_image_current_weather;
lv_obj_t * ui_page2_panel_main_label_current_temp;
lv_obj_t * ui_page2_panel_main_label_current_text;
lv_obj_t * ui_page2_panel_main_panel_temphub;
lv_obj_t * ui_page2_panel_main_label_inroom;
lv_obj_t * ui_page2_panel_main_label_inroom_temp;
lv_obj_t * ui_page2_panel_main_label_inroom_hub;
lv_obj_t * ui_page2_panel_main_image_temp;
lv_obj_t * ui_page2_panel_main_image_temp2;
lv_obj_t * ui_page2_panel_main_warn;
lv_obj_t * ui_page2_panel_main_label_current_temp2;
lv_obj_t * ui_page2_image_current_weather_day1;
lv_obj_t * ui_page2_image_current_weather_day2;
lv_obj_t * ui_page2_image_current_weather_day3;
lv_obj_t * ui_page2_panel_main_label_current_day1;
lv_obj_t * ui_page2_panel_main_label_current_day2;
lv_obj_t * ui_page2_panel_main_label_current_day3;
lv_obj_t * ui_page2_panel_main_label_current_day1_temp;
lv_obj_t * ui_page2_panel_main_label_current_day2_temp;
lv_obj_t * ui_page2_panel_main_label_current_day3_temp;
lv_obj_t * ui_page2_image_localtion;
lv_obj_t * ui_page2_label_location;
lv_obj_t * ui_page2_label_update;


// SCREEN: ui_page3_screen_monitor  监控页面
void ui_page3_screen_monitor_screen_init(void);
lv_obj_t * ui_page3_screen_monitor;
lv_obj_t * ui_page3_panel_cpu;
lv_obj_t * ui_page3_label_cpu_text;
lv_obj_t * ui_page3_arc_cpu_use;
lv_obj_t * ui_page3_image_cpu;
lv_obj_t * ui_page3_label_cpu_use_;
lv_obj_t * ui_page3_label_cpu_use_text;
lv_obj_t * ui_page3_label_cpu_use_temp;
lv_obj_t * ui_page3_label_cpu_freq;
lv_obj_t * ui_page3_label_cpu_fanspeed;
lv_obj_t * ui_page3_panel_gpu;
lv_obj_t * ui_page3_label_gpu_text;
lv_obj_t * ui_page3_arc_gpu_use;
lv_obj_t * ui_page3_image_gpu;
lv_obj_t * ui_page3_label_gpu_use;
lv_obj_t * ui_page3_label_gpu_use_text;
lv_obj_t * ui_page3_label_gpu_use_temp;
lv_obj_t * ui_page3_label_gpu_freq;
lv_obj_t * ui_page3_label_gpu_fanspeed;
lv_obj_t * ui_page3_panel_mem;
lv_obj_t * ui_page3_label_mem_text;
lv_obj_t * ui_page3_arc_mem_use;
lv_obj_t * ui_page3_label_mem_use_text;
lv_obj_t * ui_page3_image_mem;
lv_obj_t * ui_page3_label_mem_use_;
lv_obj_t * ui_page3_panel_net;
lv_obj_t * ui_page3_image_net_upload;
lv_obj_t * ui_page3_image_net_download;
lv_obj_t * ui_page3_label_download_speed;
lv_obj_t * ui_page3_label_uploadspeed;
lv_obj_t * ui_page3_label_cpu_tdp;
lv_obj_t * ui_page3_label_gpu_tdp;
lv_obj_t * ui_page3_image_gpu2;
lv_obj_t * ui_page3_image_cpu2;
lv_obj_t * ui_page3_label_cpu_fanspeed2;
lv_obj_t * ui_page3_label_net_speed_text;
lv_obj_t * ui_page3_panel_time;
lv_obj_t * ui_page3_label_cpu_fanspeed3;
lv_obj_t * ui_page3_label_cpu_fanspeed4;
lv_obj_t * ui_page3_label_download_speed2;
lv_obj_t * ui_page3_label_gpu_use2;
lv_obj_t * ui_page3_panel_others;
lv_obj_t * ui_page3_label_net_speed_text2;


// SCREEN: ui_page4_screen_set_about
void ui_page4_screen_set_about_screen_init(void);
lv_obj_t * ui_page4_screen_set_about;
lv_obj_t * ui_page4_panel_about;
lv_obj_t * ui_page4_label_about_version;
lv_obj_t * ui_page4_label_about_name;
lv_obj_t * ui_page4_label_about_designed_by;
lv_obj_t * ui_page4_panel_wifi_info;
lv_obj_t * ui_page4_label_wifi_info_title;
lv_obj_t * ui_page4_panel_wifi_connection_status;
lv_obj_t * ui_page4_label_wifi_connection_status;
lv_obj_t * ui_page4_panel_wifi_ip_address;
lv_obj_t * ui_page4_label_wifi_ip_address;
lv_obj_t * ui_page4_panel_wifi_signal_strength;
lv_obj_t * ui_page4_label_wifi_signal_strength;
lv_obj_t * ui_page4_panel_comm;
lv_obj_t * ui_page4_label_comm_titile;
lv_obj_t * ui_page4_panel_bilibili_name;
lv_obj_t * ui_page4_label_bilibili_name;
lv_obj_t * ui_page4_panel_qq_num;
lv_obj_t * ui_page4_label_qq_num;
lv_obj_t * ui_page4_panel_communication_group_;
lv_obj_t * ui_page4_label_communication_group_;
lv_obj_t * ui_page4_panel_set_mode;
lv_obj_t * ui_page4_label_set_mode_title;
lv_obj_t * ui_page4_panel_set_mode_info;
lv_obj_t * ui_page4_label_set_mode_info;

// SCREEN: ui_page5_screen_main
void ui_page5_screen_main_screen_init(void);
lv_obj_t * ui_page5_screen_main;
lv_obj_t * ui_page5_image_background;
lv_obj_t * ui_page5_label_time;
lv_obj_t * ui_page5_label_date;

// CUSTOM VARIABLES
lv_obj_t * uic_Label1;
lv_obj_t * uic_Label2;


// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_m[18] = {&ui_img_images_m00_png, &ui_img_images_m01_png, &ui_img_images_m02_png, &ui_img_images_m03_png, &ui_img_images_m04_png, &ui_img_images_m05_png, &ui_img_images_m06_png, &ui_img_images_m07_png, &ui_img_images_m08_png, &ui_img_images_m09_png, &ui_img_images_m10_png, &ui_img_images_m11_png, &ui_img_images_m12_png, &ui_img_images_m13_png, &ui_img_images_m14_png, &ui_img_images_m15_png, &ui_img_images_m16_png, &ui_img_images_m17_png};


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    
    ui_page1_Screen_Start_screen_init();
    ui_page2_screen_weather_screen_init();
    ui_page3_screen_monitor_screen_init();
    ui_page4_screen_set_about_screen_init();
    ui_page5_screen_main_screen_init();

    ui____initial_actions0 = lv_obj_create(NULL);
    
    lv_disp_load_scr(ui_page1_Screen_Start);
}
