// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page2_weather

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_page2_screen_weather
void ui_page2_screen_weather_screen_init(void);
lv_obj_t * ui_page2_screen_weather;
lv_obj_t * ui_page2_panel_main;
lv_obj_t * ui_page2_panel_main_label_date;
lv_obj_t * ui_page2_panel_main_label_week;
lv_obj_t * ui_page2_panel_main_label_lunar;
lv_obj_t * ui_page2_panel_main_label_time;
lv_obj_t * ui_page2_panel_main_label_suggest;
lv_obj_t * ui_page2_image_current_weather;
lv_obj_t * ui_page2_panel_main_label_current_temp;
lv_obj_t * ui_page2_panel_main_label_current_text;
lv_obj_t * ui_page2_panel_main_panel_temphub;
lv_obj_t * ui_page2_panel_main_label_inroom;
lv_obj_t * ui_page2_panel_main_label_inroom_temp;
lv_obj_t * ui_page2_panel_main_label_inroom_hub;
lv_obj_t * ui_page2_panel_main_image_temp;
lv_obj_t * ui_page2_panel_main_image_temp2;
lv_obj_t * ui_page2_panel_main_warn;
lv_obj_t * ui_page2_panel_main_label_current_temp2;
lv_obj_t * ui_page2_image_current_weather_day1;
lv_obj_t * ui_page2_image_current_weather_day2;
lv_obj_t * ui_page2_image_current_weather_day3;
lv_obj_t * ui_page2_panel_main_label_current_day1;
lv_obj_t * ui_page2_panel_main_label_current_day2;
lv_obj_t * ui_page2_panel_main_label_current_day3;
lv_obj_t * ui_page2_panel_main_label_current_day1_temp;
lv_obj_t * ui_page2_panel_main_label_current_day2_temp;
lv_obj_t * ui_page2_panel_main_label_current_day3_temp;
lv_obj_t * ui_page2_image_localtion;
lv_obj_t * ui_page2_label_location;
lv_obj_t * ui_page2_label_update;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_m[18] = {&ui_img_images_m00_png, &ui_img_images_m01_png, &ui_img_images_m02_png, &ui_img_images_m03_png, &ui_img_images_m04_png, &ui_img_images_m05_png, &ui_img_images_m06_png, &ui_img_images_m07_png, &ui_img_images_m08_png, &ui_img_images_m09_png, &ui_img_images_m10_png, &ui_img_images_m11_png, &ui_img_images_m12_png, &ui_img_images_m13_png, &ui_img_images_m14_png, &ui_img_images_m15_png, &ui_img_images_m16_png, &ui_img_images_m17_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_page2_screen_weather_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_page2_screen_weather);
}
