// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page2_weather

#include "ui.h"

void ui_page2_screen_weather_screen_init(void)
{
    ui_page2_screen_weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_page2_screen_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_page2_screen_weather, &ui_img_images_bizhi_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main = lv_obj_create(ui_page2_screen_weather);
    lv_obj_set_width(ui_page2_panel_main, 700);
    lv_obj_set_height(ui_page2_panel_main, 350);
    lv_obj_set_x(ui_page2_panel_main, 50);
    lv_obj_set_y(ui_page2_panel_main, 65);
    lv_obj_clear_flag(ui_page2_panel_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_page2_panel_main, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page2_panel_main, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page2_panel_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page2_panel_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_date = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_label_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_label_date, -174);
    lv_obj_set_y(ui_page2_panel_main_label_date, -128);
    lv_obj_set_align(ui_page2_panel_main_label_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_panel_main_label_date, "2024年12月02日");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_date, &ui_font_Font38px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_week = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_label_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_label_week, -183);
    lv_obj_set_y(ui_page2_panel_main_label_week, -79);
    lv_obj_set_align(ui_page2_panel_main_label_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_panel_main_label_week, "星期一");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_week, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_week, &ui_font_Font38px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_lunar = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_lunar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_label_lunar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_label_lunar, -190);
    lv_obj_set_y(ui_page2_panel_main_label_lunar, -41);
    lv_obj_set_align(ui_page2_panel_main_label_lunar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_panel_main_label_lunar, "甲辰龙年十一月初二");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_lunar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_lunar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_lunar, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_time = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_label_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_label_time, -185);
    lv_obj_set_y(ui_page2_panel_main_label_time, 36);
    lv_obj_set_align(ui_page2_panel_main_label_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_panel_main_label_time, "16:47");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_time, &ui_font_Font102px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_suggest = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_suggest, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_suggest, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_suggest, 167);
    lv_obj_set_y(ui_page2_panel_main_label_suggest, -125);
    lv_obj_set_align(ui_page2_panel_main_label_suggest, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_suggest, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_suggest, "感冒指数 易发 穿衣指数 舒适 钓鱼指数 适合");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_suggest, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_suggest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_suggest, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_image_current_weather = lv_img_create(ui_page2_panel_main);
    lv_img_set_src(ui_page2_image_current_weather, &ui_img_images_m00_png);
    lv_obj_set_width(ui_page2_image_current_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_image_current_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_image_current_weather, 40);
    lv_obj_set_y(ui_page2_image_current_weather, -73);
    lv_obj_set_align(ui_page2_image_current_weather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page2_image_current_weather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_image_current_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page2_image_current_weather, 80);

    ui_page2_panel_main_label_current_temp = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_current_temp, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_temp, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_current_temp, 113);
    lv_obj_set_y(ui_page2_panel_main_label_current_temp, -77);
    lv_obj_set_align(ui_page2_panel_main_label_current_temp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_temp, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_temp, "25℃");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_temp, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_temp, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_current_text = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_current_text, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_text, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_current_text, 127);
    lv_obj_set_y(ui_page2_panel_main_label_current_text, -52);
    lv_obj_set_align(ui_page2_panel_main_label_current_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_text, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_text, "多云 | 优 ");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_text, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_text, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_panel_temphub = lv_obj_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_panel_temphub, 200);
    lv_obj_set_height(ui_page2_panel_main_panel_temphub, 42);
    lv_obj_set_x(ui_page2_panel_main_panel_temphub, 42);
    lv_obj_set_y(ui_page2_panel_main_panel_temphub, -12);
    lv_obj_set_align(ui_page2_panel_main_panel_temphub, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_page2_panel_main_panel_temphub, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_page2_panel_main_panel_temphub, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page2_panel_main_panel_temphub, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page2_panel_main_panel_temphub, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page2_panel_main_panel_temphub, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page2_panel_main_panel_temphub, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_inroom = lv_label_create(ui_page2_panel_main_panel_temphub);
    lv_obj_set_width(ui_page2_panel_main_label_inroom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_label_inroom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_label_inroom, -10);
    lv_obj_set_y(ui_page2_panel_main_label_inroom, -10);
    lv_label_set_text(ui_page2_panel_main_label_inroom, "室内:");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_inroom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_inroom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_inroom, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_inroom_temp = lv_label_create(ui_page2_panel_main_panel_temphub);
    lv_obj_set_width(ui_page2_panel_main_label_inroom_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_label_inroom_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_label_inroom_temp, 54);
    lv_obj_set_y(ui_page2_panel_main_label_inroom_temp, -10);
    lv_label_set_text(ui_page2_panel_main_label_inroom_temp, "23℃");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_inroom_temp, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_inroom_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_inroom_temp, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_inroom_hub = lv_label_create(ui_page2_panel_main_panel_temphub);
    lv_obj_set_width(ui_page2_panel_main_label_inroom_hub, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_label_inroom_hub, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_label_inroom_hub, 135);
    lv_obj_set_y(ui_page2_panel_main_label_inroom_hub, -10);
    lv_label_set_text(ui_page2_panel_main_label_inroom_hub, "78%");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_inroom_hub, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_inroom_hub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_inroom_hub, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_image_temp = lv_img_create(ui_page2_panel_main_panel_temphub);
    lv_img_set_src(ui_page2_panel_main_image_temp, &ui_img_images_temp_png);
    lv_obj_set_width(ui_page2_panel_main_image_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_image_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_image_temp, 27);
    lv_obj_set_y(ui_page2_panel_main_image_temp, -17);
    lv_obj_add_flag(ui_page2_panel_main_image_temp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_panel_main_image_temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page2_panel_main_image_temp2 = lv_img_create(ui_page2_panel_main_panel_temphub);
    lv_img_set_src(ui_page2_panel_main_image_temp2, &ui_img_images_hub_png);
    lv_obj_set_width(ui_page2_panel_main_image_temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_panel_main_image_temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_panel_main_image_temp2, 94);
    lv_obj_set_y(ui_page2_panel_main_image_temp2, -17);
    lv_obj_add_flag(ui_page2_panel_main_image_temp2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_panel_main_image_temp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page2_panel_main_warn = lv_obj_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_warn, 112);
    lv_obj_set_height(ui_page2_panel_main_warn, 54);
    lv_obj_set_x(ui_page2_panel_main_warn, 257);
    lv_obj_set_y(ui_page2_panel_main_warn, -67);
    lv_obj_set_align(ui_page2_panel_main_warn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page2_panel_main_warn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_page2_panel_main_warn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page2_panel_main_warn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_current_temp2 = lv_label_create(ui_page2_panel_main_warn);
    lv_obj_set_width(ui_page2_panel_main_label_current_temp2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_temp2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_page2_panel_main_label_current_temp2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_temp2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_temp2, "暴雨预警");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_temp2, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_temp2, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_image_current_weather_day1 = lv_img_create(ui_page2_panel_main);
    lv_img_set_src(ui_page2_image_current_weather_day1, &ui_img_images_m01_png);
    lv_obj_set_width(ui_page2_image_current_weather_day1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_image_current_weather_day1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_image_current_weather_day1, 30);
    lv_obj_set_y(ui_page2_image_current_weather_day1, 40);
    lv_obj_set_align(ui_page2_image_current_weather_day1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page2_image_current_weather_day1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_image_current_weather_day1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page2_image_current_weather_day1, 60);

    ui_page2_image_current_weather_day2 = lv_img_create(ui_page2_panel_main);
    lv_img_set_src(ui_page2_image_current_weather_day2, &ui_img_images_m02_png);
    lv_obj_set_width(ui_page2_image_current_weather_day2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_image_current_weather_day2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_image_current_weather_day2, 150);
    lv_obj_set_y(ui_page2_image_current_weather_day2, 40);
    lv_obj_set_align(ui_page2_image_current_weather_day2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page2_image_current_weather_day2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_image_current_weather_day2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page2_image_current_weather_day2, 60);

    ui_page2_image_current_weather_day3 = lv_img_create(ui_page2_panel_main);
    lv_img_set_src(ui_page2_image_current_weather_day3, &ui_img_images_m08_png);
    lv_obj_set_width(ui_page2_image_current_weather_day3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_image_current_weather_day3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_image_current_weather_day3, 270);
    lv_obj_set_y(ui_page2_image_current_weather_day3, 40);
    lv_obj_set_align(ui_page2_image_current_weather_day3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page2_image_current_weather_day3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_image_current_weather_day3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page2_image_current_weather_day3, 60);

    ui_page2_panel_main_label_current_day1 = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_current_day1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_day1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_current_day1, 35);
    lv_obj_set_y(ui_page2_panel_main_label_current_day1, 0);
    lv_obj_set_align(ui_page2_panel_main_label_current_day1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_day1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_day1, "今天");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_day1, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_day1, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_current_day2 = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_current_day2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_day2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_current_day2, 150);
    lv_obj_set_y(ui_page2_panel_main_label_current_day2, 0);
    lv_obj_set_align(ui_page2_panel_main_label_current_day2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_day2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_day2, "星期二");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_day2, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_day2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_day2, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_current_day3 = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_current_day3, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_day3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_current_day3, 270);
    lv_obj_set_y(ui_page2_panel_main_label_current_day3, 0);
    lv_obj_set_align(ui_page2_panel_main_label_current_day3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_day3, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_day3, "星期三");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_day3, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_day3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_day3, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_current_day1_temp = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_current_day1_temp, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_day1_temp, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_current_day1_temp, 30);
    lv_obj_set_y(ui_page2_panel_main_label_current_day1_temp, 80);
    lv_obj_set_align(ui_page2_panel_main_label_current_day1_temp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_day1_temp, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_day1_temp, "9-12℃");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_day1_temp, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_day1_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_day1_temp, &ui_font_Font18px,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_current_day2_temp = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_current_day2_temp, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_day2_temp, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_current_day2_temp, 150);
    lv_obj_set_y(ui_page2_panel_main_label_current_day2_temp, 80);
    lv_obj_set_align(ui_page2_panel_main_label_current_day2_temp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_day2_temp, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_day2_temp, "9-12℃");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_day2_temp, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_day2_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_day2_temp, &ui_font_Font18px,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_panel_main_label_current_day3_temp = lv_label_create(ui_page2_panel_main);
    lv_obj_set_width(ui_page2_panel_main_label_current_day3_temp, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_page2_panel_main_label_current_day3_temp, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_page2_panel_main_label_current_day3_temp, 270);
    lv_obj_set_y(ui_page2_panel_main_label_current_day3_temp, 80);
    lv_obj_set_align(ui_page2_panel_main_label_current_day3_temp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_page2_panel_main_label_current_day3_temp, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_page2_panel_main_label_current_day3_temp, "9-12℃");
    lv_obj_set_style_text_color(ui_page2_panel_main_label_current_day3_temp, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_panel_main_label_current_day3_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_panel_main_label_current_day3_temp, &ui_font_Font18px,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_image_localtion = lv_img_create(ui_page2_screen_weather);
    lv_img_set_src(ui_page2_image_localtion, &ui_img_images_location_png);
    lv_obj_set_width(ui_page2_image_localtion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_image_localtion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_image_localtion, 5);
    lv_obj_set_y(ui_page2_image_localtion, 5);
    lv_obj_add_flag(ui_page2_image_localtion, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page2_image_localtion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page2_label_location = lv_label_create(ui_page2_screen_weather);
    lv_obj_set_width(ui_page2_label_location, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_label_location, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_label_location, -332);
    lv_obj_set_y(ui_page2_label_location, -216);
    lv_obj_set_align(ui_page2_label_location, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_label_location, "福州");
    lv_obj_set_style_text_color(ui_page2_label_location, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_label_location, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_label_location, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2_label_update = lv_label_create(ui_page2_screen_weather);
    lv_obj_set_width(ui_page2_label_update, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page2_label_update, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page2_label_update, 291);
    lv_obj_set_y(ui_page2_label_update, -221);
    lv_obj_set_align(ui_page2_label_update, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page2_label_update, "最后更新 12月02日 17:06");
    lv_obj_set_style_text_color(ui_page2_label_update, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page2_label_update, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page2_label_update, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);


}
