// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page5_main

#include "../include/ui_h/ui.h"

void ui_page5_screen_main_screen_init(void)
{
    ui_page5_screen_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_page5_screen_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page5_image_background = lv_img_create(ui_page5_screen_main);
    lv_img_set_src(ui_page5_image_background, &ui_img_images_bizhi_yejing1_png);
    lv_obj_set_width(ui_page5_image_background, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_page5_image_background, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_page5_image_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page5_image_background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page5_image_background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page5_label_time = lv_label_create(ui_page5_image_background);
    lv_obj_set_width(ui_page5_label_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page5_label_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_page5_label_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page5_label_time, "20:08");
    lv_obj_set_style_text_color(ui_page5_label_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page5_label_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page5_label_time, &ui_font_Font82px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page5_label_date = lv_label_create(ui_page5_image_background);
    lv_obj_set_width(ui_page5_label_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page5_label_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page5_label_date, 0);
    lv_obj_set_y(ui_page5_label_date, 50);
    lv_obj_set_align(ui_page5_label_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page5_label_date, "2024年12月4日");
    lv_obj_set_style_text_color(ui_page5_label_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_page5_label_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_page5_label_date, &ui_font_Font22px, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Label1 = ui_page5_label_time;
    uic_Label2 = ui_page5_label_date;

}
