// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page4_set&about

#include "../include/ui_h/ui.h"

void ui_page4_screen_set_about_screen_init(void)
{
    ui_page4_screen_set_about = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_page4_screen_set_about, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page4_panel_about = lv_obj_create(ui_page4_screen_set_about);
    lv_obj_set_width(ui_page4_panel_about, 790);
    lv_obj_set_height(ui_page4_panel_about, 40);
    lv_obj_set_x(ui_page4_panel_about, 0);
    lv_obj_set_y(ui_page4_panel_about, 215);
    lv_obj_set_align(ui_page4_panel_about, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page4_panel_about, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_page4_panel_about, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page4_panel_about, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_label_about_version = lv_label_create(ui_page4_panel_about);
    lv_obj_set_width(ui_page4_label_about_version, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_about_version, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_about_version, -10);
    lv_obj_set_y(ui_page4_label_about_version, 0);
    lv_obj_set_align(ui_page4_label_about_version, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_page4_label_about_version, "V1.0 Beta");
    lv_obj_set_style_text_font(ui_page4_label_about_version, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_label_about_name = lv_label_create(ui_page4_panel_about);
    lv_obj_set_width(ui_page4_label_about_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_about_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_page4_label_about_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page4_label_about_name, "ESPMonitor_Ultra");
    lv_obj_set_style_text_font(ui_page4_label_about_name, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_label_about_designed_by = lv_label_create(ui_page4_panel_about);
    lv_obj_set_width(ui_page4_label_about_designed_by, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_about_designed_by, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_about_designed_by, 10);
    lv_obj_set_y(ui_page4_label_about_designed_by, 0);
    lv_obj_set_align(ui_page4_label_about_designed_by, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_page4_label_about_designed_by, "Designed By Lan");
    lv_obj_set_style_text_font(ui_page4_label_about_designed_by, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_wifi_info = lv_obj_create(ui_page4_screen_set_about);
    lv_obj_set_width(ui_page4_panel_wifi_info, 260);
    lv_obj_set_height(ui_page4_panel_wifi_info, 210);
    lv_obj_set_x(ui_page4_panel_wifi_info, 5);
    lv_obj_set_y(ui_page4_panel_wifi_info, 5);
    lv_obj_clear_flag(ui_page4_panel_wifi_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_page4_panel_wifi_info, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page4_panel_wifi_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_label_wifi_info_title = lv_label_create(ui_page4_panel_wifi_info);
    lv_obj_set_width(ui_page4_label_wifi_info_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_wifi_info_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_page4_label_wifi_info_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_page4_label_wifi_info_title, "Wifi信息");
    lv_obj_set_style_text_font(ui_page4_label_wifi_info_title, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_wifi_connection_status = lv_obj_create(ui_page4_panel_wifi_info);
    lv_obj_set_width(ui_page4_panel_wifi_connection_status, 240);
    lv_obj_set_height(ui_page4_panel_wifi_connection_status, 40);
    lv_obj_set_x(ui_page4_panel_wifi_connection_status, 0);
    lv_obj_set_y(ui_page4_panel_wifi_connection_status, -30);
    lv_obj_set_align(ui_page4_panel_wifi_connection_status, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page4_panel_wifi_connection_status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page4_label_wifi_connection_status = lv_label_create(ui_page4_panel_wifi_connection_status);
    lv_obj_set_width(ui_page4_label_wifi_connection_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_wifi_connection_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_wifi_connection_status, -5);
    lv_obj_set_y(ui_page4_label_wifi_connection_status, 0);
    lv_obj_set_align(ui_page4_label_wifi_connection_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page4_label_wifi_connection_status, "Wifi：未连接");
    lv_obj_set_style_text_font(ui_page4_label_wifi_connection_status, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_wifi_ip_address = lv_obj_create(ui_page4_panel_wifi_info);
    lv_obj_set_width(ui_page4_panel_wifi_ip_address, 240);
    lv_obj_set_height(ui_page4_panel_wifi_ip_address, 40);
    lv_obj_set_x(ui_page4_panel_wifi_ip_address, 0);
    lv_obj_set_y(ui_page4_panel_wifi_ip_address, 20);
    lv_obj_set_align(ui_page4_panel_wifi_ip_address, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page4_panel_wifi_ip_address, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page4_label_wifi_ip_address = lv_label_create(ui_page4_panel_wifi_ip_address);
    lv_obj_set_width(ui_page4_label_wifi_ip_address, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_wifi_ip_address, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_wifi_ip_address, -5);
    lv_obj_set_y(ui_page4_label_wifi_ip_address, 0);
    lv_obj_set_align(ui_page4_label_wifi_ip_address, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page4_label_wifi_ip_address, "IP地址：未分配");
    lv_obj_set_style_text_font(ui_page4_label_wifi_ip_address, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_wifi_signal_strength = lv_obj_create(ui_page4_panel_wifi_info);
    lv_obj_set_width(ui_page4_panel_wifi_signal_strength, 240);
    lv_obj_set_height(ui_page4_panel_wifi_signal_strength, 40);
    lv_obj_set_x(ui_page4_panel_wifi_signal_strength, 0);
    lv_obj_set_y(ui_page4_panel_wifi_signal_strength, 70);
    lv_obj_set_align(ui_page4_panel_wifi_signal_strength, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page4_panel_wifi_signal_strength, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page4_label_wifi_signal_strength = lv_label_create(ui_page4_panel_wifi_signal_strength);
    lv_obj_set_width(ui_page4_label_wifi_signal_strength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_wifi_signal_strength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_wifi_signal_strength, -5);
    lv_obj_set_y(ui_page4_label_wifi_signal_strength, 0);
    lv_obj_set_align(ui_page4_label_wifi_signal_strength, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page4_label_wifi_signal_strength, "信号强度：无信号");
    lv_obj_set_style_text_font(ui_page4_label_wifi_signal_strength, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_comm = lv_obj_create(ui_page4_screen_set_about);
    lv_obj_set_width(ui_page4_panel_comm, 260);
    lv_obj_set_height(ui_page4_panel_comm, 210);
    lv_obj_set_x(ui_page4_panel_comm, 5);
    lv_obj_set_y(ui_page4_panel_comm, 220);
    lv_obj_clear_flag(ui_page4_panel_comm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_page4_panel_comm, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page4_panel_comm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_label_comm_titile = lv_label_create(ui_page4_panel_comm);
    lv_obj_set_width(ui_page4_label_comm_titile, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_comm_titile, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_comm_titile, 0);
    lv_obj_set_y(ui_page4_label_comm_titile, -75);
    lv_obj_set_align(ui_page4_label_comm_titile, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page4_label_comm_titile, "交流社区");
    lv_obj_set_style_text_font(ui_page4_label_comm_titile, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_bilibili_name = lv_obj_create(ui_page4_panel_comm);
    lv_obj_set_width(ui_page4_panel_bilibili_name, 240);
    lv_obj_set_height(ui_page4_panel_bilibili_name, 40);
    lv_obj_set_x(ui_page4_panel_bilibili_name, 0);
    lv_obj_set_y(ui_page4_panel_bilibili_name, -30);
    lv_obj_set_align(ui_page4_panel_bilibili_name, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page4_panel_bilibili_name, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page4_label_bilibili_name = lv_label_create(ui_page4_panel_bilibili_name);
    lv_obj_set_width(ui_page4_label_bilibili_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_bilibili_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_bilibili_name, -5);
    lv_obj_set_y(ui_page4_label_bilibili_name, 0);
    lv_obj_set_align(ui_page4_label_bilibili_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page4_label_bilibili_name, "B站：幻兰乜");
    lv_obj_set_style_text_font(ui_page4_label_bilibili_name, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_qq_num = lv_obj_create(ui_page4_panel_comm);
    lv_obj_set_width(ui_page4_panel_qq_num, 240);
    lv_obj_set_height(ui_page4_panel_qq_num, 40);
    lv_obj_set_x(ui_page4_panel_qq_num, 0);
    lv_obj_set_y(ui_page4_panel_qq_num, 20);
    lv_obj_set_align(ui_page4_panel_qq_num, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page4_panel_qq_num, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page4_label_qq_num = lv_label_create(ui_page4_panel_qq_num);
    lv_obj_set_width(ui_page4_label_qq_num, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_qq_num, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_qq_num, -5);
    lv_obj_set_y(ui_page4_label_qq_num, 0);
    lv_obj_set_align(ui_page4_label_qq_num, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page4_label_qq_num, "QQ：522076290");
    lv_obj_set_style_text_font(ui_page4_label_qq_num, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_communication_group_ = lv_obj_create(ui_page4_panel_comm);
    lv_obj_set_width(ui_page4_panel_communication_group_, 240);
    lv_obj_set_height(ui_page4_panel_communication_group_, 40);
    lv_obj_set_x(ui_page4_panel_communication_group_, 0);
    lv_obj_set_y(ui_page4_panel_communication_group_, 70);
    lv_obj_set_align(ui_page4_panel_communication_group_, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page4_panel_communication_group_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page4_label_communication_group_ = lv_label_create(ui_page4_panel_communication_group_);
    lv_obj_set_width(ui_page4_label_communication_group_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_communication_group_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_communication_group_, -5);
    lv_obj_set_y(ui_page4_label_communication_group_, 0);
    lv_obj_set_align(ui_page4_label_communication_group_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page4_label_communication_group_, "交流群：xxxxxxx");
    lv_obj_set_style_text_font(ui_page4_label_communication_group_, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_set_mode = lv_obj_create(ui_page4_screen_set_about);
    lv_obj_set_width(ui_page4_panel_set_mode, 525);
    lv_obj_set_height(ui_page4_panel_set_mode, 425);
    lv_obj_set_x(ui_page4_panel_set_mode, -5);
    lv_obj_set_y(ui_page4_panel_set_mode, 5);
    lv_obj_set_align(ui_page4_panel_set_mode, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_page4_panel_set_mode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_page4_panel_set_mode, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page4_panel_set_mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_label_set_mode_title = lv_label_create(ui_page4_panel_set_mode);
    lv_obj_set_width(ui_page4_label_set_mode_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_set_mode_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_set_mode_title, 10);
    lv_obj_set_y(ui_page4_label_set_mode_title, 0);
    lv_obj_set_align(ui_page4_label_set_mode_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_page4_label_set_mode_title, "配置引导");
    lv_obj_set_style_text_font(ui_page4_label_set_mode_title, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_panel_set_mode_info = lv_obj_create(ui_page4_panel_set_mode);
    lv_obj_set_width(ui_page4_panel_set_mode_info, 490);
    lv_obj_set_height(ui_page4_panel_set_mode_info, 350);
    lv_obj_set_x(ui_page4_panel_set_mode_info, 0);
    lv_obj_set_y(ui_page4_panel_set_mode_info, 20);
    lv_obj_set_align(ui_page4_panel_set_mode_info, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page4_panel_set_mode_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_page4_panel_set_mode_info, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page4_panel_set_mode_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page4_label_set_mode_info = lv_label_create(ui_page4_panel_set_mode_info);
    lv_obj_set_width(ui_page4_label_set_mode_info, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page4_label_set_mode_info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page4_label_set_mode_info, 10);
    lv_obj_set_y(ui_page4_label_set_mode_info, 0);
    lv_obj_set_align(ui_page4_label_set_mode_info, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_page4_label_set_mode_info, "WIFI配网已开启\n请用微信扫码");
    lv_obj_set_style_text_font(ui_page4_label_set_mode_info, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);


}
