// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page3_monitor

#include "../include/ui_h/ui.h"

void ui_page3_screen_monitor_screen_init(void)
{
    ui_page3_screen_monitor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_page3_screen_monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_page3_screen_monitor, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page3_screen_monitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_panel_cpu = lv_obj_create(ui_page3_screen_monitor);
    lv_obj_set_width(ui_page3_panel_cpu, 390);
    lv_obj_set_height(ui_page3_panel_cpu, 220);
    lv_obj_set_x(ui_page3_panel_cpu, 5);
    lv_obj_set_y(ui_page3_panel_cpu, 5);
    lv_obj_clear_flag(ui_page3_panel_cpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page3_label_cpu_text = lv_label_create(ui_page3_panel_cpu);
    lv_obj_set_width(ui_page3_label_cpu_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_text, -2);
    lv_obj_set_y(ui_page3_label_cpu_text, -77);
    lv_obj_set_align(ui_page3_label_cpu_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_text, "处理器");
    lv_obj_set_style_text_font(ui_page3_label_cpu_text, &ui_font_Font48px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_arc_cpu_use = lv_arc_create(ui_page3_panel_cpu);
    lv_obj_set_width(ui_page3_arc_cpu_use, 150);
    lv_obj_set_height(ui_page3_arc_cpu_use, 150);
    lv_obj_set_x(ui_page3_arc_cpu_use, -95);
    lv_obj_set_y(ui_page3_arc_cpu_use, 41);
    lv_obj_set_align(ui_page3_arc_cpu_use, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_page3_arc_cpu_use, 50);
    lv_obj_set_style_arc_color(ui_page3_arc_cpu_use, lv_color_hex(0xACACBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_page3_arc_cpu_use, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_page3_arc_cpu_use, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page3_arc_cpu_use, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_page3_image_cpu = lv_img_create(ui_page3_panel_cpu);
    lv_img_set_src(ui_page3_image_cpu, &ui_img_images_cpu_png);
    lv_obj_set_width(ui_page3_image_cpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_image_cpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_image_cpu, -96);
    lv_obj_set_y(ui_page3_image_cpu, 9);
    lv_obj_set_align(ui_page3_image_cpu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page3_image_cpu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page3_image_cpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page3_image_cpu, 128);

    ui_page3_label_cpu_use_ = lv_label_create(ui_page3_panel_cpu);
    lv_obj_set_width(ui_page3_label_cpu_use_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_use_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_use_, -95);
    lv_obj_set_y(ui_page3_label_cpu_use_, 55);
    lv_obj_set_align(ui_page3_label_cpu_use_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_use_, "78");
    lv_obj_set_style_text_font(ui_page3_label_cpu_use_, &ui_font_Font48px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_cpu_use_text = lv_label_create(ui_page3_panel_cpu);
    lv_obj_set_width(ui_page3_label_cpu_use_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_use_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_use_text, -95);
    lv_obj_set_y(ui_page3_label_cpu_use_text, 90);
    lv_obj_set_align(ui_page3_label_cpu_use_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_use_text, "使用率%");
    lv_obj_set_style_text_font(ui_page3_label_cpu_use_text, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_cpu_use_temp = lv_label_create(ui_page3_panel_cpu);
    lv_obj_set_width(ui_page3_label_cpu_use_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_use_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_use_temp, 66);
    lv_obj_set_y(ui_page3_label_cpu_use_temp, -13);
    lv_obj_set_align(ui_page3_label_cpu_use_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_use_temp, "温度: 65℃");
    lv_obj_set_style_text_font(ui_page3_label_cpu_use_temp, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_cpu_freq = lv_label_create(ui_page3_panel_cpu);
    lv_obj_set_width(ui_page3_label_cpu_freq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_freq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_freq, 84);
    lv_obj_set_y(ui_page3_label_cpu_freq, 35);
    lv_obj_set_align(ui_page3_label_cpu_freq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_freq, "主频: 5.9GHz");
    lv_obj_set_style_text_font(ui_page3_label_cpu_freq, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_cpu_fanspeed = lv_label_create(ui_page3_panel_cpu);
    lv_obj_set_width(ui_page3_label_cpu_fanspeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_fanspeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_fanspeed, 96);
    lv_obj_set_y(ui_page3_label_cpu_fanspeed, 81);
    lv_obj_set_align(ui_page3_label_cpu_fanspeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_fanspeed, "风扇: 1300RPM");
    lv_obj_set_style_text_font(ui_page3_label_cpu_fanspeed, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_panel_gpu = lv_obj_create(ui_page3_screen_monitor);
    lv_obj_set_width(ui_page3_panel_gpu, 390);
    lv_obj_set_height(ui_page3_panel_gpu, 220);
    lv_obj_set_x(ui_page3_panel_gpu, -5);
    lv_obj_set_y(ui_page3_panel_gpu, 5);
    lv_obj_set_align(ui_page3_panel_gpu, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_page3_panel_gpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page3_label_gpu_text = lv_label_create(ui_page3_panel_gpu);
    lv_obj_set_width(ui_page3_label_gpu_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_gpu_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_gpu_text, -2);
    lv_obj_set_y(ui_page3_label_gpu_text, -77);
    lv_obj_set_align(ui_page3_label_gpu_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_gpu_text, "显卡");
    lv_obj_set_style_text_font(ui_page3_label_gpu_text, &ui_font_Font48px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_arc_gpu_use = lv_arc_create(ui_page3_panel_gpu);
    lv_obj_set_width(ui_page3_arc_gpu_use, 150);
    lv_obj_set_height(ui_page3_arc_gpu_use, 150);
    lv_obj_set_x(ui_page3_arc_gpu_use, -95);
    lv_obj_set_y(ui_page3_arc_gpu_use, 41);
    lv_obj_set_align(ui_page3_arc_gpu_use, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_page3_arc_gpu_use, 50);
    lv_obj_set_style_arc_color(ui_page3_arc_gpu_use, lv_color_hex(0xFF8A01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_page3_arc_gpu_use, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_page3_arc_gpu_use, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_page3_arc_gpu_use, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_page3_arc_gpu_use, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page3_arc_gpu_use, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_page3_image_gpu = lv_img_create(ui_page3_panel_gpu);
    lv_img_set_src(ui_page3_image_gpu, &ui_img_1298787339);
    lv_obj_set_width(ui_page3_image_gpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_image_gpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_image_gpu, -96);
    lv_obj_set_y(ui_page3_image_gpu, 9);
    lv_obj_set_align(ui_page3_image_gpu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page3_image_gpu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page3_image_gpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page3_image_gpu, 128);

    ui_page3_label_gpu_use = lv_label_create(ui_page3_panel_gpu);
    lv_obj_set_width(ui_page3_label_gpu_use, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_gpu_use, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_gpu_use, -95);
    lv_obj_set_y(ui_page3_label_gpu_use, 55);
    lv_obj_set_align(ui_page3_label_gpu_use, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_gpu_use, "12");
    lv_obj_set_style_text_font(ui_page3_label_gpu_use, &ui_font_Font48px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_gpu_use_text = lv_label_create(ui_page3_panel_gpu);
    lv_obj_set_width(ui_page3_label_gpu_use_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_gpu_use_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_gpu_use_text, -95);
    lv_obj_set_y(ui_page3_label_gpu_use_text, 90);
    lv_obj_set_align(ui_page3_label_gpu_use_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_gpu_use_text, "使用率%");
    lv_obj_set_style_text_font(ui_page3_label_gpu_use_text, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_gpu_use_temp = lv_label_create(ui_page3_panel_gpu);
    lv_obj_set_width(ui_page3_label_gpu_use_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_gpu_use_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_gpu_use_temp, 66);
    lv_obj_set_y(ui_page3_label_gpu_use_temp, -13);
    lv_obj_set_align(ui_page3_label_gpu_use_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_gpu_use_temp, "温度: 35℃");
    lv_obj_set_style_text_font(ui_page3_label_gpu_use_temp, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_gpu_freq = lv_label_create(ui_page3_panel_gpu);
    lv_obj_set_width(ui_page3_label_gpu_freq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_gpu_freq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_gpu_freq, 84);
    lv_obj_set_y(ui_page3_label_gpu_freq, 35);
    lv_obj_set_align(ui_page3_label_gpu_freq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_gpu_freq, "主频: 2.4GHz");
    lv_obj_set_style_text_font(ui_page3_label_gpu_freq, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_gpu_fanspeed = lv_label_create(ui_page3_panel_gpu);
    lv_obj_set_width(ui_page3_label_gpu_fanspeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_gpu_fanspeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_gpu_fanspeed, 96);
    lv_obj_set_y(ui_page3_label_gpu_fanspeed, 81);
    lv_obj_set_align(ui_page3_label_gpu_fanspeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_gpu_fanspeed, "风扇: 1240RPM");
    lv_obj_set_style_text_font(ui_page3_label_gpu_fanspeed, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_panel_mem = lv_obj_create(ui_page3_screen_monitor);
    lv_obj_set_width(ui_page3_panel_mem, 260);
    lv_obj_set_height(ui_page3_panel_mem, 190);
    lv_obj_set_x(ui_page3_panel_mem, 5);
    lv_obj_set_y(ui_page3_panel_mem, 230);
    lv_obj_clear_flag(ui_page3_panel_mem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page3_label_mem_text = lv_label_create(ui_page3_panel_mem);
    lv_obj_set_width(ui_page3_label_mem_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_mem_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_mem_text, -4);
    lv_obj_set_y(ui_page3_label_mem_text, -60);
    lv_obj_set_align(ui_page3_label_mem_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_mem_text, "内存");
    lv_obj_set_style_text_font(ui_page3_label_mem_text, &ui_font_Font48px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_arc_mem_use = lv_arc_create(ui_page3_panel_mem);
    lv_obj_set_width(ui_page3_arc_mem_use, 120);
    lv_obj_set_height(ui_page3_arc_mem_use, 120);
    lv_obj_set_x(ui_page3_arc_mem_use, -8);
    lv_obj_set_y(ui_page3_arc_mem_use, 26);
    lv_obj_set_align(ui_page3_arc_mem_use, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_page3_arc_mem_use, 50);
    lv_obj_set_style_arc_color(ui_page3_arc_mem_use, lv_color_hex(0xACACBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_page3_arc_mem_use, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_page3_arc_mem_use, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page3_arc_mem_use, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_page3_label_mem_use_text = lv_label_create(ui_page3_panel_mem);
    lv_obj_set_width(ui_page3_label_mem_use_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_mem_use_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_mem_use_text, -9);
    lv_obj_set_y(ui_page3_label_mem_use_text, 82);
    lv_obj_set_align(ui_page3_label_mem_use_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_mem_use_text, "使用率%");
    lv_obj_set_style_text_font(ui_page3_label_mem_use_text, &ui_font_Font18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_image_mem = lv_img_create(ui_page3_panel_mem);
    lv_img_set_src(ui_page3_image_mem, &ui_img_images_ram_png);
    lv_obj_set_width(ui_page3_image_mem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_image_mem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_image_mem, -9);
    lv_obj_set_y(ui_page3_image_mem, 0);
    lv_obj_set_align(ui_page3_image_mem, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page3_image_mem, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page3_image_mem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page3_image_mem, 128);

    ui_page3_label_mem_use_ = lv_label_create(ui_page3_panel_mem);
    lv_obj_set_width(ui_page3_label_mem_use_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_mem_use_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_mem_use_, -8);
    lv_obj_set_y(ui_page3_label_mem_use_, 40);
    lv_obj_set_align(ui_page3_label_mem_use_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_mem_use_, "42");
    lv_obj_set_style_text_font(ui_page3_label_mem_use_, &ui_font_Font48px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_panel_net = lv_obj_create(ui_page3_screen_monitor);
    lv_obj_set_width(ui_page3_panel_net, 260);
    lv_obj_set_height(ui_page3_panel_net, 190);
    lv_obj_set_x(ui_page3_panel_net, 1);
    lv_obj_set_y(ui_page3_panel_net, 85);
    lv_obj_set_align(ui_page3_panel_net, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page3_panel_net, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page3_image_net_upload = lv_img_create(ui_page3_panel_net);
    lv_img_set_src(ui_page3_image_net_upload, &ui_img_images_upload_png);
    lv_obj_set_width(ui_page3_image_net_upload, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_image_net_upload, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_image_net_upload, 31);
    lv_obj_set_y(ui_page3_image_net_upload, 70);
    lv_obj_set_align(ui_page3_image_net_upload, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page3_image_net_upload, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page3_image_net_upload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page3_image_net_upload, 100);

    ui_page3_image_net_download = lv_img_create(ui_page3_panel_net);
    lv_img_set_src(ui_page3_image_net_download, &ui_img_images_download_png);
    lv_obj_set_width(ui_page3_image_net_download, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_image_net_download, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_image_net_download, -101);
    lv_obj_set_y(ui_page3_image_net_download, 71);
    lv_obj_set_align(ui_page3_image_net_download, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page3_image_net_download, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page3_image_net_download, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page3_image_net_download, 100);

    ui_page3_label_download_speed = lv_label_create(ui_page3_panel_net);
    lv_obj_set_width(ui_page3_label_download_speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_download_speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_download_speed, -33);
    lv_obj_set_y(ui_page3_label_download_speed, 72);
    lv_obj_set_align(ui_page3_label_download_speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_download_speed, "68.3MB/S");
    lv_obj_set_style_text_font(ui_page3_label_download_speed, &ui_font_Font18mkzpx, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_uploadspeed = lv_label_create(ui_page3_panel_net);
    lv_obj_set_width(ui_page3_label_uploadspeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_uploadspeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_uploadspeed, 87);
    lv_obj_set_y(ui_page3_label_uploadspeed, 72);
    lv_obj_set_align(ui_page3_label_uploadspeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_uploadspeed, "1.4MB/S");
    lv_obj_set_style_text_font(ui_page3_label_uploadspeed, &ui_font_Font18mkzpx, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_cpu_tdp = lv_label_create(ui_page3_panel_net);
    lv_obj_set_width(ui_page3_label_cpu_tdp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_tdp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_tdp, -73);
    lv_obj_set_y(ui_page3_label_cpu_tdp, 0);
    lv_obj_set_align(ui_page3_label_cpu_tdp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_tdp, "78.2W");
    lv_obj_set_style_text_font(ui_page3_label_cpu_tdp, &ui_font_Font18mkzpx, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_gpu_tdp = lv_label_create(ui_page3_panel_net);
    lv_obj_set_width(ui_page3_label_gpu_tdp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_gpu_tdp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_gpu_tdp, 72);
    lv_obj_set_y(ui_page3_label_gpu_tdp, -2);
    lv_obj_set_align(ui_page3_label_gpu_tdp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_gpu_tdp, "150.2W");
    lv_obj_set_style_text_font(ui_page3_label_gpu_tdp, &ui_font_Font18mkzpx, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_image_gpu2 = lv_img_create(ui_page3_panel_net);
    lv_img_set_src(ui_page3_image_gpu2, &ui_img_1298787339);
    lv_obj_set_width(ui_page3_image_gpu2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_image_gpu2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_image_gpu2, 70);
    lv_obj_set_y(ui_page3_image_gpu2, -44);
    lv_obj_set_align(ui_page3_image_gpu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page3_image_gpu2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page3_image_gpu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page3_image_gpu2, 128);

    ui_page3_image_cpu2 = lv_img_create(ui_page3_panel_net);
    lv_img_set_src(ui_page3_image_cpu2, &ui_img_images_cpu_png);
    lv_obj_set_width(ui_page3_image_cpu2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_image_cpu2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_image_cpu2, -72);
    lv_obj_set_y(ui_page3_image_cpu2, -40);
    lv_obj_set_align(ui_page3_image_cpu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page3_image_cpu2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_page3_image_cpu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_page3_image_cpu2, 128);

    ui_page3_label_cpu_fanspeed2 = lv_label_create(ui_page3_panel_net);
    lv_obj_set_width(ui_page3_label_cpu_fanspeed2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_fanspeed2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_fanspeed2, -3);
    lv_obj_set_y(ui_page3_label_cpu_fanspeed2, -74);
    lv_obj_set_align(ui_page3_label_cpu_fanspeed2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_fanspeed2, "功耗");
    lv_obj_set_style_text_font(ui_page3_label_cpu_fanspeed2, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_net_speed_text = lv_label_create(ui_page3_panel_net);
    lv_obj_set_width(ui_page3_label_net_speed_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_net_speed_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_net_speed_text, -53);
    lv_obj_set_y(ui_page3_label_net_speed_text, 35);
    lv_obj_set_align(ui_page3_label_net_speed_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_net_speed_text, "网络速度:");
    lv_obj_set_style_text_font(ui_page3_label_net_speed_text, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_panel_time = lv_obj_create(ui_page3_screen_monitor);
    lv_obj_set_width(ui_page3_panel_time, 260);
    lv_obj_set_height(ui_page3_panel_time, 190);
    lv_obj_set_x(ui_page3_panel_time, 265);
    lv_obj_set_y(ui_page3_panel_time, 85);
    lv_obj_set_align(ui_page3_panel_time, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page3_panel_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page3_label_cpu_fanspeed3 = lv_label_create(ui_page3_panel_time);
    lv_obj_set_width(ui_page3_label_cpu_fanspeed3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_fanspeed3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_fanspeed3, -80);
    lv_obj_set_y(ui_page3_label_cpu_fanspeed3, -62);
    lv_obj_set_align(ui_page3_label_cpu_fanspeed3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_fanspeed3, "日期");
    lv_obj_set_style_text_font(ui_page3_label_cpu_fanspeed3, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_cpu_fanspeed4 = lv_label_create(ui_page3_panel_time);
    lv_obj_set_width(ui_page3_label_cpu_fanspeed4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_cpu_fanspeed4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_cpu_fanspeed4, -80);
    lv_obj_set_y(ui_page3_label_cpu_fanspeed4, 17);
    lv_obj_set_align(ui_page3_label_cpu_fanspeed4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_cpu_fanspeed4, "时间");
    lv_obj_set_style_text_font(ui_page3_label_cpu_fanspeed4, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_download_speed2 = lv_label_create(ui_page3_panel_time);
    lv_obj_set_width(ui_page3_label_download_speed2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_download_speed2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_download_speed2, -4);
    lv_obj_set_y(ui_page3_label_download_speed2, -20);
    lv_obj_set_align(ui_page3_label_download_speed2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_download_speed2, "2024年12月3日");
    lv_obj_set_style_text_font(ui_page3_label_download_speed2, &ui_font_Font18mkzpx, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_label_gpu_use2 = lv_label_create(ui_page3_panel_time);
    lv_obj_set_width(ui_page3_label_gpu_use2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_gpu_use2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_gpu_use2, 0);
    lv_obj_set_y(ui_page3_label_gpu_use2, 63);
    lv_obj_set_align(ui_page3_label_gpu_use2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_gpu_use2, "11:22");
    lv_obj_set_style_text_font(ui_page3_label_gpu_use2, &ui_font_Font48px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page3_panel_others = lv_obj_create(ui_page3_screen_monitor);
    lv_obj_set_width(ui_page3_panel_others, 790);
    lv_obj_set_height(ui_page3_panel_others, 50);
    lv_obj_set_x(ui_page3_panel_others, 6);
    lv_obj_set_y(ui_page3_panel_others, -5);
    lv_obj_set_align(ui_page3_panel_others, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_page3_panel_others, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page3_label_net_speed_text2 = lv_label_create(ui_page3_panel_others);
    lv_obj_set_width(ui_page3_label_net_speed_text2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_page3_label_net_speed_text2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_page3_label_net_speed_text2, -8);
    lv_obj_set_y(ui_page3_label_net_speed_text2, 4);
    lv_obj_set_align(ui_page3_label_net_speed_text2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_page3_label_net_speed_text2, "东北风2级 23℃");
    lv_obj_set_style_text_font(ui_page3_label_net_speed_text2, &ui_font_Font24px, LV_PART_MAIN | LV_STATE_DEFAULT);


}
