// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page5_main

#ifndef _PAGE5_MAIN_UI_H
#define _PAGE5_MAIN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_page5_screen_main
void ui_page5_screen_main_screen_init(void);
extern lv_obj_t * ui_page5_screen_main;
extern lv_obj_t * ui_page5_image_background;
extern lv_obj_t * ui_page5_label_time;
extern lv_obj_t * ui_page5_label_date;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_Label1;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_bizhi_yejing1_png);    // assets/images/bizhi_yejing1.png
LV_IMG_DECLARE(ui_img_images_bizhi_yanhua1_png);    // assets/images/bizhi_yanhua1.png

// FONTS
LV_FONT_DECLARE(ui_font_Font22px);
LV_FONT_DECLARE(ui_font_Font82px);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
