// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page3_monitor

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_page3_screen_monitor
void ui_page3_screen_monitor_screen_init(void);
lv_obj_t * ui_page3_screen_monitor;
lv_obj_t * ui_page3_panel_cpu;
lv_obj_t * ui_page3_label_cpu_text;
lv_obj_t * ui_page3_arc_cpu_use;
lv_obj_t * ui_page3_image_cpu;
lv_obj_t * ui_page3_label_cpu_use_;
lv_obj_t * ui_page3_label_cpu_use_text;
lv_obj_t * ui_page3_label_cpu_use_temp;
lv_obj_t * ui_page3_label_cpu_freq;
lv_obj_t * ui_page3_label_cpu_fanspeed;
lv_obj_t * ui_page3_panel_gpu;
lv_obj_t * ui_page3_label_gpu_text;
lv_obj_t * ui_page3_arc_gpu_use;
lv_obj_t * ui_page3_image_gpu;
lv_obj_t * ui_page3_label_gpu_use;
lv_obj_t * ui_page3_label_gpu_use_text;
lv_obj_t * ui_page3_label_gpu_use_temp;
lv_obj_t * ui_page3_label_gpu_freq;
lv_obj_t * ui_page3_label_gpu_fanspeed;
lv_obj_t * ui_page3_panel_mem;
lv_obj_t * ui_page3_label_mem_text;
lv_obj_t * ui_page3_arc_mem_use;
lv_obj_t * ui_page3_label_mem_use_text;
lv_obj_t * ui_page3_image_mem;
lv_obj_t * ui_page3_label_mem_use_;
lv_obj_t * ui_page3_panel_net;
lv_obj_t * ui_page3_image_net_upload;
lv_obj_t * ui_page3_image_net_download;
lv_obj_t * ui_page3_label_download_speed;
lv_obj_t * ui_page3_label_uploadspeed;
lv_obj_t * ui_page3_label_cpu_tdp;
lv_obj_t * ui_page3_label_gpu_tdp;
lv_obj_t * ui_page3_image_gpu2;
lv_obj_t * ui_page3_image_cpu2;
lv_obj_t * ui_page3_label_cpu_fanspeed2;
lv_obj_t * ui_page3_label_net_speed_text;
lv_obj_t * ui_page3_panel_time;
lv_obj_t * ui_page3_label_cpu_fanspeed3;
lv_obj_t * ui_page3_label_cpu_fanspeed4;
lv_obj_t * ui_page3_label_download_speed2;
lv_obj_t * ui_page3_label_gpu_use2;
lv_obj_t * ui_page3_panel_others;
lv_obj_t * ui_page3_label_net_speed_text2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_page3_screen_monitor_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_page3_screen_monitor);
}
