// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: page3_monitor

#ifndef _PAGE3_MONITOR_UI_H
#define _PAGE3_MONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_page3_screen_monitor
void ui_page3_screen_monitor_screen_init(void);
extern lv_obj_t * ui_page3_screen_monitor;
extern lv_obj_t * ui_page3_panel_cpu;
extern lv_obj_t * ui_page3_label_cpu_text;
extern lv_obj_t * ui_page3_arc_cpu_use;
extern lv_obj_t * ui_page3_image_cpu;
extern lv_obj_t * ui_page3_label_cpu_use_;
extern lv_obj_t * ui_page3_label_cpu_use_text;
extern lv_obj_t * ui_page3_label_cpu_use_temp;
extern lv_obj_t * ui_page3_label_cpu_freq;
extern lv_obj_t * ui_page3_label_cpu_fanspeed;
extern lv_obj_t * ui_page3_panel_gpu;
extern lv_obj_t * ui_page3_label_gpu_text;
extern lv_obj_t * ui_page3_arc_gpu_use;
extern lv_obj_t * ui_page3_image_gpu;
extern lv_obj_t * ui_page3_label_gpu_use;
extern lv_obj_t * ui_page3_label_gpu_use_text;
extern lv_obj_t * ui_page3_label_gpu_use_temp;
extern lv_obj_t * ui_page3_label_gpu_freq;
extern lv_obj_t * ui_page3_label_gpu_fanspeed;
extern lv_obj_t * ui_page3_panel_mem;
extern lv_obj_t * ui_page3_label_mem_text;
extern lv_obj_t * ui_page3_arc_mem_use;
extern lv_obj_t * ui_page3_label_mem_use_text;
extern lv_obj_t * ui_page3_image_mem;
extern lv_obj_t * ui_page3_label_mem_use_;
extern lv_obj_t * ui_page3_panel_net;
extern lv_obj_t * ui_page3_image_net_upload;
extern lv_obj_t * ui_page3_image_net_download;
extern lv_obj_t * ui_page3_label_download_speed;
extern lv_obj_t * ui_page3_label_uploadspeed;
extern lv_obj_t * ui_page3_label_cpu_tdp;
extern lv_obj_t * ui_page3_label_gpu_tdp;
extern lv_obj_t * ui_page3_image_gpu2;
extern lv_obj_t * ui_page3_image_cpu2;
extern lv_obj_t * ui_page3_label_cpu_fanspeed2;
extern lv_obj_t * ui_page3_label_net_speed_text;
extern lv_obj_t * ui_page3_panel_time;
extern lv_obj_t * ui_page3_label_cpu_fanspeed3;
extern lv_obj_t * ui_page3_label_cpu_fanspeed4;
extern lv_obj_t * ui_page3_label_download_speed2;
extern lv_obj_t * ui_page3_label_gpu_use2;
extern lv_obj_t * ui_page3_panel_others;
extern lv_obj_t * ui_page3_label_net_speed_text2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_cpu_png);    // assets/images/CPU.png
LV_IMG_DECLARE(ui_img_1298787339);    // assets/images/gpu-mining.png
LV_IMG_DECLARE(ui_img_images_ram_png);    // assets/images/RAM.png
LV_IMG_DECLARE(ui_img_images_upload_png);    // assets/images/upload.png
LV_IMG_DECLARE(ui_img_images_download_png);    // assets/images/download.png

// FONTS
LV_FONT_DECLARE(ui_font_Font18mkzpx);
LV_FONT_DECLARE(ui_font_Font18px);
LV_FONT_DECLARE(ui_font_Font24px);
LV_FONT_DECLARE(ui_font_Font48px);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
